Allow PARTITION/SUBPARTITION name syntax to use more unreserved keywords
The PARTITION/SUBPARTITION name syntax parsing currently allows only a
subset of unreserved keywords. This separate list was created back in
the early GPDB 4.0 days. This causes unexpected errors such as:

postgres=# CREATE TABLE foopart (a int, b int) PARTITION BY RANGE(b) (DEFAULT PARTITION at);
ERROR:  syntax error at or near "at"
LINE 1: ...(a int, b int) PARTITION BY RANGE(b) (DEFAULT PARTITION at);

In the above example, "at" is an unreserved keyword that is not in the
PartitionColId list. The obvious workaround is to double quote it but
functions such as pg_get_partition_def() which runs quote_ident() on
all identifiers will not double quote it. The partition DDL being
dumped from various tools (e.g. pg_dumpall, gpbackup, etc.) would
error on restore because of this scenario. This was found from a
reported gprestore failure where the partition DDL had "at" as a
SUBPARTITION name.

To fix this, I have added a supplemental list
PartitionIdentExtraKeyword that is added to the PartitionColId
list. The unreserved keywords EXPAND, REPLICA, TABLESPACE, and
VALIDATE are excluded because of partitioning syntax conflicts (from
my bad interpretation of the bison errors).

The gpdb-dev thread:
https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/A3sBh8ClWF0